title: Install Python 3
hero_image: images/banner.png
description: ingredient for how to install python 3
duration: 1 # possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: 
technologies: "python"
steps:
  - title: Install Python 3