---
title: How to install Python 3
hero_image: images/banner.png
description: Instructions for how to install Python 3
duration: 1 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests:
technologies: "python"
steps:
  - 
    title: Install Python 3
